# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjezbe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knjiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
            ],
        ),
    ]
