# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vjezbe', '0002_knjiga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knjiga',
            options={'permissions': (('mozeMjenjat', 'moze mjenjat podatke o knjizi'), ('mozeDodat', 'moze dodatvati knjige'))},
        ),
    ]
